# key_mapping = {
#         'first_name': "What is your first name? ",
#         'last_name': "What is your last name? ",
#         'middle_name': "What is your middle name, if any? ",
#         'former_name': "Do you have a former name? (e.g. a maiden name) ",
#         'street_address': "What is your street address IN TEXAS, including any apartment numbers? If none, describe where you live. ",
#         'city': "What city (in TX)? ",
#         'county': "What county (in TX)? ",
#         'mailing_address': "Do you have a mailing address different than the one described (Y or N)? ",
#         'mailing_address_city': 'What city? ',
#         'mailing_address_state': 'What state? ',
#         'mailing_address_zip': 'Zip code? ',
#         'former_res': 'What is the city AND county of your former residence IN TEXAS? ',
#         'birth_month': 'What month were you born? ',
#         'birth_day': 'What day were you born? ',
#         'birth_year': 'What year were you born? ',
#         'phone': 'What is your phone number? ',
#         'license': 'What is your TX driver\'s license number OR TX Personal ID number? ',
#         'ssn': 'What are the LAST 4 digits of your social security number? ',
#         'citizen': 'Are you a United State Citizen (Y or N)? ',
#         'age': 'Will you be 18 years of age on or before election day? ',
#         'election_worker': 'Are you interested in becoming an election worker (Y or N)? '
# }

prompts = [
        "What is your first name? ",
        "What is your last name? ",
        # "What is your middle name, if any? ",
        # "Do you have a former name? (e.g. a maiden name) ",
        # "What is your street address IN TEXAS, including any apartment numbers? If none, describe where you live. ",
        # "What city (in TX)? ",
        # "What county (in TX)? ",
        # "Do you have a mailing address different than the one described (Y or N)? ",
        # 'What city? ',
        # 'What state? ',
        # 'Zip code? ',
        # 'What is the city AND county of your former residence IN TEXAS? ',
        # 'What month were you born? ',
        # 'What day were you born? ',
        # 'What year were you born? ',
        # 'What is your phone number? ',
        # 'What is your TX driver\'s license number OR TX Personal ID number? ',
        # 'What are the LAST 4 digits of your social security number? ',
        # 'Are you a United States Citizen (Y or N)? ',
        # 'Will you be 18 years of age on or before election day? ',
        # 'Are you interested in becoming an election worker (Y or N)? '
]

prompts2 = {
        "What is your first name? ": "first_name",
        "What is your last name? ": "last_name",
        "What is your middle name, if any? ": "middle_name",
        "Do you have a former name? (e.g. a maiden name) ": "former_name",
        "What is your street address IN TEXAS, including any apartment numbers? If none, describe where you live. ": "street_address",
        "What city (in TX)? ": "city",
        "What county (in TX)? ": "county",
        "Do you have a mailing address different than the one described (Y or N)? ": "street_address_2",
        'What city? ': "city_2",
        'What state? ': "state",
        'Zip code? ': "zip_code_2",
        'What is the city AND county of your former residence IN TEXAS? ': "former_res",
        'What month were you born? ': "birth_month",
        'What day were you born? ': "birth_day",
        'What year were you born? ': "birth_year",
        'What is your phone number? ': "phone",
        'What is your TX driver\'s license number OR TX Personal ID number? ': "license",
        'What are the LAST 4 digits of your social security number? ': "ssn",
        'Are you a United States Citizen (Y or N)? ': "citizenship",
        'Will you be 18 years of age on or before election day? ': "voting_age",
        'Are you interested in becoming an election worker (Y or N)? ': "election_worker",
        "Do you identify as male or female (optional)? ": "gender"
}

mailing_address_prompts = [
        "What is your mailing address (if different than your residence address)? ",
        "Residence address city? ",
        "Residence address state? ",
        "Residence address zip code? ",
    ]