prompts = {
        # "Why are you completing this form? ":"why",
        "What is your first name? ": "first_name",
        "What is your last name? ": "last_name",
        "What is your middle name, if any? ": "middle_name",
        "What is your former name, if any? (e.g. a maiden name) ": "former_name",
        "What is your street address IN TEXAS, including any apartment numbers? If none, describe where you live. ": "street_address",
        "What city (in TX)? ": "city",
        "What county (in TX)? ": "county",
        "What is your zip code? ": 'zip_code',
        "Mailing (street) address different than the one described (optional)? ": "street_address_2",
        'Secondary address city (optional)? ': "city_2",
        'Secondary address state (optional)? ': "state",
        'Secondary address zip code (optional)? ': "zip_code_2",
        'What is the city AND county of your former residence IN TEXAS? ': "former_res",
        'What month were you born (MM)? ': "birth_month",
        'What day were you born (DD)? ': "birth_day",
        'What year were you born (YYYY)? ': "birth_year",
        'What is your phone number (optional)? ': "phone",
        'Have you been issued a TX driver\'s license or social security number (SSN) (Y or N)? ': 'no_id',
        'What is your TX driver\'s license number OR TX Personal ID number? ': "license",
        'What are the LAST 4 digits of your social security number (provide if no TX driver\'s license or Personal Identification cannot be given)? ': "ssn",
        'Are you a United States Citizen (Y or N)? ': "citizenship",
        'Will you be 18 years of age on or before election day (Y or N)? ': "voting_age",
        'Are you interested in becoming an election worker (Y or N)? ': "election_worker",
        "Do you identify as male or female (optional)(M or F)? ": "gender"
}
person_attributes = {
        "why": None,
        "first_name":None, 
        "last_name":None,
        "middle_name":None,
        "former_name":None,
        "street_address":None,
        "city":None,
        "county":None,
        "zip_code":None,
        "street_address_2":None,
        "city_2":None,
        "state":None,
        "zip_code_2":None,
        "former_res":None,
        "birth_month":None,
        "birth_day":None,
        "birth_year":None,
        "phone":None,
        'phone_2':None,
        'phone_3':None,
        "license":None,
        "ssn":None,
        "no_id":None,
        "date":None,
        "deputy":None,
        "secondary_date":None,
        "applicant_agent":None,
        "receipt":None,
        "volunteer":None,
        "deputy_no":None,
        "date_3":None,
        "print":None,
        "reset":None,
        'citizenship':None,
        "voting_age":None,
        "election_worker":None,
        "gender":None
        }

attribute_keys = [
            "why", "last_name", "first_name", "middle_name", "former_name",
            "street_address", "city", "county", "zip_code", "street_address_2",
            "city_2", "state", "zip_code_2", "former_res", "birth_month", "birth_day",
            "birth_year", "phone", "phone_2", "phone_3", "license", "ssn", "no_id", "date", "deputy", 'secondary_date', "applicant_agent", "receipt", "volunteer", "deputy_no", "date_3", "print", "reset",
            "citizenship", "voting_age", "election_worker", "gender", "new_application"
        ]