const dataKeys = {
    "why": "",
    "first_name":"", 
    "last_name":"",
    "middle_name":"",
    "former_name":"",
    "street_address":"",
    "city":"",
    "county":"",
    "zip_code":"",
    "street_address_2": "", 
    "city_2":"", 
    "state":"", 
    "zip_code_2":"", 
    "former_res":"", 
    "birth_month":"",
    "birth_day":"",
    "birth_year":"",
    "phone":"",
    'phone_2':"",
    'phone_3':"",
    "license":"",
    "ssn":"",
    "no_id":"",
    "date":"",
    "deputy":"",
    "secondary_date":"",
    "applicant_agent":"",
    "receipt":"",
    "volunteer":"", /* need to add */
    "deputy_no":"",
    "date_3":"",
    "print":"",
    "reset":"",
    'citizenship':"",
    "voting_age":"",
    "election_worker":"", 
    "gender":"" 
    }

export default dataKeys
